name: TestMXFL
favicon: null
layout_spectrum: 0.7984823
typography_spectrum: 0.07419899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#c2c2c2'
    - '#797979'
    - '#fd0000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
