typography_spectrum: 0.8093
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#c2c2c2'
    - '#797979'
    - '#fd0000'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73851
analytics:
  google: null
  facebook: null
  twitter: null
name: MXFL
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About MXFL
    id: 34dbdaf9-202c-4107-b349-e20bf89520ec
    type: content
  - name: MXFL Rules and Regulations
    id: aae5bbb2-5ef2-4035-8814-0bda2e002903
    type: content
  - name: MXFL League Calendar
    url: 'http://leaguecalendar.maddenxtremefootball.com/index.html'
    type: external
  - name: MXFL Network
    id: e74ef5bc-9872-45a9-a0b9-a34786561ec1
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Madden Xtreme Football League
description: Home of the Maximus
purpose: []
