title: Madden Xtreme Football League
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.1875
  rhythmicContrast: 0
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#c2c2c2'
    - '#797979'
    - '#fd0000'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TestMXFL
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.07419899
layout_spectrum: 0.8836425
