analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#c2c2c2'
    - '#797979'
    - '#fd0000'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0.518549
  saturation: 1
cta: {}
layout_spectrum: 0.7984823
name: TestMXFL
opengraph: {}
purpose: []
typography_spectrum: 0.07419899
